### ISSUE TITLE
Strange warning

### ISSUE THREAD

**Issue by shadow2560** [FIX94/c2w_patcher#1]
Helo,

I'm encountering a strange message with the version 1.1. The version 1.0 work well but here is the messages of the v1.1:

"
cafe2wii Patcher v1.1 by FIX94
Read in key
Read in c2w.img
Patched LT_IOP2X at 8a98
Patched LT_COMPAT_MEMCTRL_STATE at 9bf4
Patched LT_SYSPROT at e474
WARNING: Did not apply c2w.img patches as expected!
All Done!
Press enter to exit
"

Why this warning? I use it with Wiivc Injector Script and manualy and the same warning message show up.

Thanks.

**Comment by FIX94** [comment]
WOW, how did I include the IOP2X patch? I didnt even mean for that thing to be included! really I am greatly confused, I guess I somehow tested it but never removed it from my code...

**Comment by FIX94** [comment]
well I now moved it into its own option and disabled it by default as it was designed, thanks a lot for pointing this out.
